language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t derniageng/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true derniageng/react-test npm test

after_success:
  - docker build -t derniageng/multi-client ./client
  - docker build -t derniageng/multi-nginx ./nginx
  - docker build -t derniageng/multi-server ./server
  - docker build -t derniageng/multi-worker ./worker
  # login docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those image to docker hub 
  - docker push derniageng/multi-client
  - docker push derniageng/multi-nginx
  - docker push derniageng/multi-server
  - docker push derniageng/multi-worker 
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-767397880410'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY